JUtils: JUtils.Extensions.ColorExtensions Class Reference
JUtils.Extensions.ColorExtensions Class Reference
Static Public Member Functions
static bool Equals (this Color self, Color other, float threshold)
Compare 2 colors with a threshold
static bool Equals2 (this Color self, Color other, float threshold)
Compare 2 colors with a threshold, probably worse but idk
static bool TContains (this IEnumerable< Color > self, Color other, float threshold)
Compare 2 colors with a threshold
Static Private Member Functions
static bool CompareThreshold (float a, float b, float threshold)
Detailed Description
Definition at line 9 of file ColorExtensions.cs.
Member Function Documentation
CompareThreshold()
static bool JUtils.Extensions.ColorExtensions.CompareThreshold (float a, float b, float threshold) inline static private
Definition at line 11 of file ColorExtensions.cs.
         {
             return Mathf.Abs(a - b) < threshold;
         }
Referenced by JUtils.Extensions.ColorExtensions.Equals(), and JUtils.Extensions.ColorExtensions.Equals2().
Equals()
static bool JUtils.Extensions.ColorExtensions.Equals (this Color self, Color other, float threshold) inline static
Compare 2 colors with a threshold
Definition at line 20 of file ColorExtensions.cs.
         {
             return CompareThreshold(self.r, other.r, threshold) &&
                    CompareThreshold(self.g, other.g, threshold) &&
                    CompareThreshold(self.b, other.b, threshold);
         }
References JUtils.Extensions.ColorExtensions.CompareThreshold().
Equals2()
static bool JUtils.Extensions.ColorExtensions.Equals2 (this Color self, Color other, float threshold) inline static
Compare 2 colors with a threshold, probably worse but idk
Definition at line 31 of file ColorExtensions.cs.
         {
             return CompareThreshold(
                 self.r + self.g + self.b,
                 other.r + other.g + other.b,
                 threshold
             );
         }
References JUtils.Extensions.ColorExtensions.CompareThreshold().
TContains()
static bool JUtils.Extensions.ColorExtensions.TContains (this IEnumerable< Color > self, Color other, float threshold) inline static
Compare 2 colors with a threshold
Definition at line 44 of file ColorExtensions.cs.
         {
             return self.Any(color => color.Equals(other, threshold));
         }
The documentation for this class was generated from the following file:
JUtils/Extensions/ColorExtensions.cs