JUtils: JUtils.FSM.StateMachine Class Reference
JUtils.FSM.StateMachine Class Reference abstract
Classes
struct QueueEntry
Public Member Functions
void GoToNoState ()
Clears the queue and triggers OnNoState>
void GoToState (State state, StateData data)
Clears the StateQueue and goes to the given state
void GoToState< T > (StateData data)
Clears the StateQueue and goes to the given state
bool AddToQueue (State state, StateData data)
Adds a new state to the queue
void AddToQueue< T > (StateData data)
Adds a new state to the queue
void ContinueQueue ()
Deactivate the current state and go to the next one
T FindState< T > ()
Find a state within the child objects of this state-machine, if autoCreateStates is enabled, it will automatically instantiate the state
bool TryFindState< T > (out T state)
Try finding a state within the child objects of this state-machine, if autoCreateStates is enabled, it will automatically instantiate that state
void GoToState (State state)
Clears the StateQueue and goes to the given state
void GoToState< T, T1 > (T state, T1 arg1)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2 > (T state, T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
void GoToState< T > ()
Adds a new state to the queue
void GoToState< T, T1 > (T1 arg1)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2 > (T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
void GoToState< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2)
Adds a new state to the queue
void GoToState< T, T1 > (StateRef< T > stateRef, T1 arg1)
Adds a new state to the queue
void GoToState< T > (StateRef< T > stateRef)
Adds a new state to the queue
void AddToQueue< T > (T state)
Adds a new state to the queue
void AddToQueue< T, T1 > (T state, T1 arg1)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (T state, T1 arg1, T2 arg2)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
void AddToQueue< T > ()
Adds a new state to the queue
void AddToQueue< T, T1 > (T1 arg1)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (T1 arg1, T2 arg2)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2)
Adds a new state to the queue
void AddToQueue< T, T1 > (StateRef< T > stateRef, T1 arg1)
Adds a new state to the queue
void AddToQueue< T > (StateRef< T > stateRef)
Adds a new state to the queue
Protected Member Functions
virtual void Reset ()
virtual void OnValidate ()
override void OnActivate ()
override void OnDeactivate ()
override void Awake ()
virtual void Start ()
abstract void OnNoState ()
Protected Member Functions inherited from JUtils.FSM.State< T1, T2, T3 >
void Deactivate ()
StateRef< T > Ref< T > ()
virtual void ActiveUpdate ()
virtual void Update ()
override void OnActivate ()
abstract void OnActivate (T a)
override void OnActivate ()
abstract void OnActivate (T1 a, T2 b)
override void OnActivate ()
abstract void OnActivate (T1 a, T2 b, T3 c)
Protected Attributes
State CurrentState
Queue< QueueEntry > StateQueue = new ()
Events
Action< State > OnStateChanged
Events inherited from JUtils.FSM.State< T1, T2, T3 >
Action< State > OnStateActivate
Action< State > OnStateDeactivate
Private Member Functions
void Log (object message)
Private Attributes
bool showLogs
bool autoActivate
bool autoCreateStates = true
Additional Inherited Members
Package Functions inherited from JUtils.FSM.State< T1, T2, T3 >
void ActivateState ()
void DeactivateState ()
Properties inherited from JUtils.FSM.State< T1, T2, T3 >
bool IsActive [get, private set]
float TimeInState [get]
float UnscaledTimeInState [get]
StateMachine StateMachine [get, set]
StateData Data [get, set]
Detailed Description
Definition at line 10 of file StateMachine.cs.
Member Function Documentation
AddToQueue()
bool JUtils.FSM.StateMachine.AddToQueue (State state, StateData data) inline
Adds a new state to the queue
Returns
True if the added state has been set as the current state
Definition at line 78 of file StateMachine.cs.
         {
             if (!state) {
                 Log($"Tried to add Null state");
             }
             else {
                 StateQueue.Enqueue(new QueueEntry {State = state, Data = data ?? new StateData()});
                 Log($"Add '{state.GetType().Name}' to the queue");
             }
             if (CurrentState) return false;
             ContinueQueue();
             return true;
         }
References JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.StateMachine.CurrentState, JUtils.FSM.State< T1, T2, T3 >.Data, JUtils.FSM.StateMachine.Log(), and JUtils.FSM.StateMachine.StateQueue.
Referenced by JUtils.FSM.StateMachine.AddToQueue< T >(), and JUtils.FSM.StateMachine.GoToState().
AddToQueue< T >() [1/4]
void JUtils.FSM.StateMachine.AddToQueue< T > ()
Adds a new state to the queue
Type Constraints
T : State
T : AddToQueue<T>
T : new
T : StateData()
AddToQueue< T >() [2/4]
void JUtils.FSM.StateMachine.AddToQueue< T > (StateData data) inline
Adds a new state to the queue
Type Constraints
T : State
Definition at line 97 of file StateMachine.cs.
                                                           : State
         {
             if (TryFindState(out T state)) AddToQueue(state, data);
         }
References JUtils.FSM.StateMachine.AddToQueue().
AddToQueue< T >() [3/4]
void JUtils.FSM.StateMachine.AddToQueue< T > (StateRef< T > stateRef)
Adds a new state to the queue
Type Constraints
T : State
T : AddToQueue<T>()
AddToQueue< T >() [4/4]
void JUtils.FSM.StateMachine.AddToQueue< T > (T state)
Adds a new state to the queue
Type Constraints
T : State
T : AddToQueue
T : state
T : new
T : StateData()
AddToQueue< T, T1 >() [1/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1 > (StateRef< T > stateRef, T1 arg1)
Adds a new state to the queue
Type Constraints
T : State<T1>
T : AddToQueue<T>
T : new
T : StateData
T : arg1
AddToQueue< T, T1 >() [2/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1 > (T state, T1 arg1)
Adds a new state to the queue
Type Constraints
T : State<T1>
T : AddToQueue
T : state
T : new
T : StateData
T : arg1
AddToQueue< T, T1 >() [3/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1 > (T1 arg1)
Adds a new state to the queue
Type Constraints
T : State<T1>
T : AddToQueue<T>
T : new
T : StateData
T : arg1
AddToQueue< T, T1, T2 >() [1/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : AddToQueue<T>
T : new
T : StateData
T : arg1
T : arg2
AddToQueue< T, T1, T2 >() [2/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2 > (T state, T1 arg1, T2 arg2)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : AddToQueue
T : state
T : new
T : StateData
T : arg1
T : arg2
AddToQueue< T, T1, T2 >() [3/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2 > (T1 arg1, T2 arg2)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : AddToQueue<T>
T : new
T : StateData
T : arg1
T : arg2
AddToQueue< T, T1, T2, T3 >() [1/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
T : AddToQueue<T>
T : new
T : StateData
T : arg1
T : arg2
T : arg3
AddToQueue< T, T1, T2, T3 >() [2/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
T : AddToQueue
T : state
T : new
T : StateData
T : arg1
T : arg2
T : arg3
AddToQueue< T, T1, T2, T3 >() [3/3]
void JUtils.FSM.StateMachine.AddToQueue< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
T : AddToQueue<T>
T : new
T : StateData
T : arg1
T : arg2
T : arg3
Awake()
override void JUtils.FSM.StateMachine.Awake () inline protected virtual
Reimplemented from JUtils.FSM.State< T1, T2, T3 >.
Definition at line 185 of file StateMachine.cs.
         {
             if (!autoActivate) base.Awake();
         }
References JUtils.FSM.StateMachine.autoActivate.
ContinueQueue()
void JUtils.FSM.StateMachine.ContinueQueue () inline
Deactivate the current state and go to the next one
Definition at line 106 of file StateMachine.cs.
         {
             if (!IsActive) {
                 Debug.LogWarning($"[{GetType().Name}] Tried to continue the state queue, but the this state machine is not active!");
                 return;
             }
             if (CurrentState) {
                 Log($"Deactivate state '{CurrentState.GetType().Name}'");
                 CurrentState.DeactivateState();
             }
             if (StateQueue.TryDequeue(out QueueEntry entry)) {
                 State state = entry.State;
                 state.Data         = entry.Data;
                 state.StateMachine = this;
                 CurrentState       = state;
                 Log($"Activate state '{state.GetType().Name}'");
                 state.ActivateState();
                 OnStateChanged?.Invoke(state);
             }
             else {
                 Log($"Firing function '{nameof(OnNoState)}'");
                 CurrentState = null;
                 OnNoState();
             }
         }
References JUtils.FSM.State< T1, T2, T3 >.ActivateState(), JUtils.FSM.StateMachine.CurrentState, JUtils.FSM.State< T1, T2, T3 >.Data, JUtils.FSM.State< T1, T2, T3 >.DeactivateState(), JUtils.FSM.State< T1, T2, T3 >.IsActive, JUtils.FSM.StateMachine.Log(), JUtils.FSM.StateMachine.OnNoState(), JUtils.FSM.StateMachine.OnStateChanged, JUtils.FSM.State< T1, T2, T3 >.StateMachine, and JUtils.FSM.StateMachine.StateQueue.
Referenced by JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.State< T1, T2, T3 >.Deactivate(), JUtils.FSM.StateMachine.GoToNoState(), JUtils.FSM.StateMachine.GoToState(), and JUtils.FSM.StateMachine.OnActivate().
FindState< T >()
T JUtils.FSM.StateMachine.FindState< T > () inline
Find a state within the child objects of this state-machine, if autoCreateStates is enabled, it will automatically instantiate the state
Type Constraints
T : State
Definition at line 140 of file StateMachine.cs.
                                         : State
         {
             TryFindState(out T state);
             return state;
         }
GoToNoState()
void JUtils.FSM.StateMachine.GoToNoState () inline
Clears the queue and triggers OnNoState>
Definition at line 40 of file StateMachine.cs.
         {
             Log("Forcibly go to no state");
             StateQueue.Clear();
             ContinueQueue();
         }
References JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.StateMachine.Log(), and JUtils.FSM.StateMachine.StateQueue.
Referenced by JUtils.FSM.StateMachine.GoToState().
GoToState() [1/2]
void JUtils.FSM.StateMachine.GoToState (State state)
Clears the StateQueue and goes to the given state
GoToState() [2/2]
void JUtils.FSM.StateMachine.GoToState (State state, StateData data) inline
Clears the StateQueue and goes to the given state
Definition at line 51 of file StateMachine.cs.
         {
             if (!state) {
                 GoToNoState();
                 return;
             }
             Log($"Force go to state '{state.GetType().Name}'");
             StateQueue.Clear();
             if (!AddToQueue(state, data)) ContinueQueue();
         }
References JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.StateMachine.GoToNoState(), JUtils.FSM.StateMachine.Log(), and JUtils.FSM.StateMachine.StateQueue.
Referenced by JUtils.FSM.StateMachine.GoToState< T >().
GoToState< T >() [1/3]
void JUtils.FSM.StateMachine.GoToState< T > ()
Adds a new state to the queue
Type Constraints
T : State
T : GoToState<T>
T : new
T : StateData()
GoToState< T >() [2/3]
void JUtils.FSM.StateMachine.GoToState< T > (StateData data) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
Definition at line 67 of file StateMachine.cs.
                                                          : State
         {
             if (!TryFindState(out T state)) return;
             GoToState(state, data);
         }
References JUtils.FSM.StateMachine.GoToState().
GoToState< T >() [3/3]
void JUtils.FSM.StateMachine.GoToState< T > (StateRef< T > stateRef)
Adds a new state to the queue
Type Constraints
T : State
T : GoToState<T>()
GoToState< T, T1 >() [1/3]
void JUtils.FSM.StateMachine.GoToState< T, T1 > (StateRef< T > stateRef, T1 arg1)
Adds a new state to the queue
Type Constraints
T : State<T1>
T : GoToState<T>
T : new
T : StateData
T : arg1
GoToState< T, T1 >() [2/3]
void JUtils.FSM.StateMachine.GoToState< T, T1 > (T state, T1 arg1)
Clears the StateQueue and goes to the given state
Type Constraints
T : State<T1>
T : GoToState
T : state
T : new
T : StateData
T : arg1
GoToState< T, T1 >() [3/3]
void JUtils.FSM.StateMachine.GoToState< T, T1 > (T1 arg1)
Clears the StateQueue and goes to the given state
Type Constraints
T : State<T1>
T : GoToState<T>
T : new
T : StateData
T : arg1
GoToState< T, T1, T2 >() [1/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : GoToState<T>
T : new
T : StateData
T : arg1
T : arg2
GoToState< T, T1, T2 >() [2/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2 > (T state, T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : GoToState
T : state
T : new
T : StateData
T : arg1
T : arg2
GoToState< T, T1, T2 >() [3/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2 > (T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : GoToState<T>
T : new
T : StateData
T : arg1
T : arg2
GoToState< T, T1, T2, T3 >() [1/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
T : GoToState<T>
T : new
T : StateData
T : arg1
T : arg2
T : arg3
GoToState< T, T1, T2, T3 >() [2/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : T3
T : GoToState
T : state
T : new
T : StateData
T : arg1
T : arg2
T : arg3
GoToState< T, T1, T2, T3 >() [3/3]
void JUtils.FSM.StateMachine.GoToState< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : T3
T : GoToState<T>
T : new
T : StateData
T : arg1
T : arg2
T : arg3
Log()
void JUtils.FSM.StateMachine.Log (object message) inline private
Definition at line 201 of file StateMachine.cs.
         {
             if (showLogs) {
                 Debug.Log($"[{GetType().Name}] : {message}", this);
             }
         }
References JUtils.FSM.StateMachine.showLogs.
Referenced by JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.StateMachine.GoToNoState(), JUtils.FSM.StateMachine.GoToState(), and JUtils.FSM.StateMachine.TryFindState< T >().
OnActivate()
override void JUtils.FSM.StateMachine.OnActivate () inline protected virtual
Implements JUtils.FSM.State< T1, T2, T3 >.
Definition at line 169 of file StateMachine.cs.
         {
             ContinueQueue();
         }
References JUtils.FSM.StateMachine.ContinueQueue().
OnDeactivate()
override void JUtils.FSM.StateMachine.OnDeactivate () inline protected virtual
Implements JUtils.FSM.State< T1, T2, T3 >.
Definition at line 175 of file StateMachine.cs.
         {
             StateQueue.Clear();
             if (!CurrentState) return;
             CurrentState.DeactivateState();
             CurrentState = null;
         }
References JUtils.FSM.StateMachine.CurrentState, JUtils.FSM.State< T1, T2, T3 >.DeactivateState(), and JUtils.FSM.StateMachine.StateQueue.
OnNoState()
abstract void JUtils.FSM.StateMachine.OnNoState () protected pure virtual
Referenced by JUtils.FSM.StateMachine.ContinueQueue().
OnValidate()
virtual void JUtils.FSM.StateMachine.OnValidate () inline protected virtual
Definition at line 28 of file StateMachine.cs.
         {
             if (!autoActivate || !this.GetComponentInParentsDirect<StateMachine>()) return;
             autoActivate = false;
             Debug.LogWarning($"[{GetType().Name}] : {nameof(autoActivate)} cannot be enabled when this is a sub-statemachine");
         }
References JUtils.FSM.StateMachine.autoActivate.
Reset()
virtual void JUtils.FSM.StateMachine.Reset () inline protected virtual
Definition at line 22 of file StateMachine.cs.
         {
             autoActivate = !GetComponentInParent<StateMachine>();
         }
References JUtils.FSM.StateMachine.autoActivate.
Start()
virtual void JUtils.FSM.StateMachine.Start () inline protected virtual
Definition at line 191 of file StateMachine.cs.
         {
             if (autoActivate) { ActivateState(); }
         }
References JUtils.FSM.State< T1, T2, T3 >.ActivateState(), and JUtils.FSM.StateMachine.autoActivate.
TryFindState< T >()
bool JUtils.FSM.StateMachine.TryFindState< T > (out T state) inline
Try finding a state within the child objects of this state-machine, if autoCreateStates is enabled, it will automatically instantiate that state
Type Constraints
T : State
Definition at line 150 of file StateMachine.cs.
                                                          : State
         {
             if (this.TryGetComponentInDirectChildren(out state))
                 return true;
             if (!autoCreateStates) {
                 Debug.LogError($"[{GetType().Name}] : Tried to load state '{typeof(T).Name}' but it does not exist");
                 return false;
             }
             Log($"Created new state '{typeof(T).Name}'");
             GameObject obj = new (typeof(T).Name);
             obj.transform.parent = transform;
             state = obj.AddComponent<T>();
             return true;
         }
References JUtils.FSM.StateMachine.autoCreateStates, and JUtils.FSM.StateMachine.Log().
Member Data Documentation
autoActivate
bool JUtils.FSM.StateMachine.autoActivate private
Definition at line 13 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.Awake(), JUtils.FSM.StateMachine.OnValidate(), JUtils.FSM.StateMachine.Reset(), and JUtils.FSM.StateMachine.Start().
autoCreateStates
bool JUtils.FSM.StateMachine.autoCreateStates = true private
Definition at line 14 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.TryFindState< T >().
CurrentState
State JUtils.FSM.StateMachine.CurrentState protected
Definition at line 18 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.StateMachine.ContinueQueue(), and JUtils.FSM.StateMachine.OnDeactivate().
showLogs
bool JUtils.FSM.StateMachine.showLogs private
Definition at line 12 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.Log().
StateQueue
Queue<QueueEntry> JUtils.FSM.StateMachine.StateQueue = new () protected
Definition at line 19 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.StateMachine.GoToNoState(), JUtils.FSM.StateMachine.GoToState(), and JUtils.FSM.StateMachine.OnDeactivate().
Event Documentation
OnStateChanged
Action<State> JUtils.FSM.StateMachine.OnStateChanged
Definition at line 16 of file StateMachine.cs.
Referenced by JUtils.FSM.StateMachine.ContinueQueue().
The documentation for this class was generated from the following files:
JUtils/FSM/StateMachine.cs
JUtils/FSM/StateMachine.Helpers.cs