JUtils: JUtils.ObjectPool Class Reference
JUtils.ObjectPool Class Reference
A simple implementation for an object pool
Public Member Functions
PoolItem SpawnItem ()
Spawn a pooled item
PoolItem SpawnItem (Vector3 localPosition)
Spawn a pooled item
PoolItem SpawnItem (Vector3 localPosition, Transform parent)
Spawn a pooled item
PoolItem SpawnItem (Transform parent)
Spawn a pooled item
PoolItem SpawnItem (Vector3 localPosition, Quaternion localRotation, Transform parent=null)
Spawn a pooled item
bool TryGetItem (out PoolItem item)
Get a pooled item, returns false if the pool can't auto expand and if there are no items left
int InstantiateNewItems (int amount=-1)
Request X amount of items to be made
void SetTemplate (PoolItem newTemplate)
Change the template of this object pool
Properties
PoolItem template [get]
IEnumerable< PoolItem > activePoolItems [get]
IEnumerable< PoolItem > freePoolItems [get]
Detailed Description
A simple implementation for an object pool
Disabling this component may result in erroneous behaviour
Member Function Documentation
InstantiateNewItems()
int JUtils.ObjectPool.InstantiateNewItems (int amount = -1) inline
Request X amount of items to be made
SetTemplate()
void JUtils.ObjectPool.SetTemplate (PoolItem newTemplate) inline
Change the template of this object pool
Template can only change when no object has been created
SpawnItem() [1/5]
PoolItem JUtils.ObjectPool.SpawnItem () inline
Spawn a pooled item
SpawnItem() [2/5]
PoolItem JUtils.ObjectPool.SpawnItem (Transform parent) inline
Spawn a pooled item
References JUtils.ObjectPool.SpawnItem().
SpawnItem() [3/5]
PoolItem JUtils.ObjectPool.SpawnItem (Vector3 localPosition) inline
Spawn a pooled item
References JUtils.ObjectPool.SpawnItem().
SpawnItem() [4/5]
PoolItem JUtils.ObjectPool.SpawnItem (Vector3 localPosition, Quaternion localRotation, Transform parent = null) inline
Spawn a pooled item
SpawnItem() [5/5]
PoolItem JUtils.ObjectPool.SpawnItem (Vector3 localPosition, Transform parent) inline
Spawn a pooled item
References JUtils.ObjectPool.SpawnItem().
TryGetItem()
bool JUtils.ObjectPool.TryGetItem (out PoolItem item) inline
Get a pooled item, returns false if the pool can't auto expand and if there are no items left
Property Documentation
activePoolItems
IEnumerable<PoolItem> JUtils.ObjectPool.activePoolItems get
freePoolItems
IEnumerable<PoolItem> JUtils.ObjectPool.freePoolItems get
template
PoolItem JUtils.ObjectPool.template get
The documentation for this class was generated from the following file:
ObjectPool.cs