JUtils: JUtils.State< T1, T2, T3 > Class Template Reference
JUtils.State< T1, T2, T3 > Class Template Reference abstract
A simple state that can be driven by stateMachine
Protected Member Functions
void Deactivate ()
Deactivate this state and make the state-machine continue its queue
abstract void OnActivate ()
Gets called when the state activates
abstract void OnDeactivate ()
Gets called when the sate deactivates
StateRef< T > Ref< T > ()
Used for making typed argument adding to states prettier
virtual void ActiveUpdate ()
Only runs the Update() function when the state is active
virtual void Awake ()
virtual void Update ()
override void OnActivate ()
abstract void OnActivate (T param)
override void OnActivate ()
abstract void OnActivate (T1 param1, T2 param2)
override void OnActivate ()
abstract void OnActivate (T1 param1, T2 param2, T3 param3)
Properties
bool isActive [get]
bool isActivating [get]
Is set to true while the state is activating
bool isDeactivating [get]
Is set to true while the state is deactivating
StateMachine stateMachine [get, set]
The reference of this state's state machine
float timeInState [get]
Get the amount of seconds that this state is active. Returns 0 if the state is not active
float unscaledTimeInState [get]
Get the amount of unscaled seconds that this state is active. Returns 0 if the state is not active
StateData stateData [get]
Events
Action< State > onStateActivate
Action< State > onStateDeactivate
Detailed Description
A simple state that can be driven by stateMachine
State with 3 type-safe arguments
State with 2 type-safe arguments
State with 1 type-safe arguments
Member Function Documentation
ActiveUpdate()
virtual void JUtils.State< T1, T2, T3 >.ActiveUpdate () inline protected virtual
Only runs the Update() function when the state is active
Awake()
virtual void JUtils.State< T1, T2, T3 >.Awake () inline protected virtual
Reimplemented in JUtils.StateMachine.
References JUtils.State< T1, T2, T3 >.isActive.
Deactivate()
void JUtils.State< T1, T2, T3 >.Deactivate () inline protected
Deactivate this state and make the state-machine continue its queue
References JUtils.StateMachine.ContinueQueue(), JUtils.State< T1, T2, T3 >.isActive, and JUtils.State< T1, T2, T3 >.stateMachine.
OnActivate() [1/7]
abstract void JUtils.State< T1, T2, T3 >.OnActivate () protected pure virtual
Gets called when the state activates
OnActivate() [2/7]
override void JUtils.State< T1, T2, T3 >.OnActivate () inline protected
References JUtils.State< T1, T2, T3 >.OnActivate(), and JUtils.State< T1, T2, T3 >.stateData.
OnActivate() [3/7]
override void JUtils.State< T1, T2, T3 >.OnActivate () inline protected
References JUtils.State< T1, T2, T3 >.OnActivate(), and JUtils.State< T1, T2, T3 >.stateData.
OnActivate() [4/7]
override void JUtils.State< T1, T2, T3 >.OnActivate () inline protected
References JUtils.State< T1, T2, T3 >.OnActivate(), and JUtils.State< T1, T2, T3 >.stateData.
OnActivate() [5/7]
abstract void JUtils.State< T1, T2, T3 >.OnActivate (T param) protected pure virtual
OnActivate() [6/7]
abstract void JUtils.State< T1, T2, T3 >.OnActivate (T1 param1, T2 param2) protected pure virtual
OnActivate() [7/7]
abstract void JUtils.State< T1, T2, T3 >.OnActivate (T1 param1, T2 param2, T3 param3) protected pure virtual
OnDeactivate()
abstract void JUtils.State< T1, T2, T3 >.OnDeactivate () protected pure virtual
Gets called when the sate deactivates
Ref< T >()
StateRef<T> JUtils.State< T1, T2, T3 >.Ref< T > () inline protected
Used for making typed argument adding to states prettier
Template Parameters
T The type we want the ref from
StateMachine.AddToQueue(Ref&#60;TeleportState>, location);
>
Type Constraints
T : State
Update()
virtual void JUtils.State< T1, T2, T3 >.Update () inline protected virtual
References JUtils.State< T1, T2, T3 >.ActiveUpdate(), and JUtils.State< T1, T2, T3 >.isActive.
Property Documentation
isActivating
bool JUtils.State< T1, T2, T3 >.isActivating get
Is set to true while the state is activating
isActive
bool JUtils.State< T1, T2, T3 >.isActive get
isDeactivating
bool JUtils.State< T1, T2, T3 >.isDeactivating get
Is set to true while the state is deactivating
stateData
StateData JUtils.State< T1, T2, T3 >.stateData get protected
stateMachine
StateMachine JUtils.State< T1, T2, T3 >.stateMachine get set
The reference of this state's state machine
timeInState
float JUtils.State< T1, T2, T3 >.timeInState get
Get the amount of seconds that this state is active. Returns 0 if the state is not active
unscaledTimeInState
float JUtils.State< T1, T2, T3 >.unscaledTimeInState get
Get the amount of unscaled seconds that this state is active. Returns 0 if the state is not active
Event Documentation
onStateActivate
Action<State> JUtils.State< T1, T2, T3 >.onStateActivate
onStateDeactivate
Action<State> JUtils.State< T1, T2, T3 >.onStateDeactivate
The documentation for this class was generated from the following file:
State.cs