JUtils: JUtils.Coroutines Class Reference
JUtils.Coroutines Class Reference
Static Public Member Functions
static WaitForSeconds WaitForSeconds (float seconds)
Faster alternative to WaitForSeconds, caches the object. This will permanently cache the instance unless removed with Coroutines.wfsDictionary
static WaitForSecondsRealtime WaitForSecondsRealtime (float seconds)
Faster alternative to creating a new WaitForSecondsRealtime, caches the object. This will permanently cache the instance unless removed with Coroutines.wfsRtDictionary
static WaitForFixedUpdate WaitForFixedUpdate ()
Return the cached WaitForFixedUpdate instance
static WaitForEndOfFrame WaitForEndOfFrame ()
Return the cached WaitForFixedUpdate instance
static CoroutineCatcher Catcher (IEnumerator coroutine)
Returns a CoroutineCatcher
static Coroutine RunNextFrame (Action action)
Run a action in the next frame
static Coroutine RunDelay (float delay, Action action)
Run a action after a certain amount of seconds; – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
static Coroutine RunDelay (TimeSpan delay, Action action)
Run a action after a certain amount of seconds – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
static Coroutine Run (IEnumerator routine)
Run a routine on the JUtils Object – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
Properties
static Dictionary< float, WaitForSeconds > wfsDictionary [get]
static Dictionary< float, WaitForSecondsRealtime > wfsRtDictionary [get]
Static Private Attributes
static Dictionary< float, WaitForSeconds > _wfsDictionary
static Dictionary< float, WaitForSecondsRealtime > _wfsRtDictionary
static WaitForFixedUpdate _waitForFixedUpdate
static WaitForEndOfFrame _waitForEndOfFrame
Detailed Description
Definition at line 11 of file Coroutines.cs.
Member Function Documentation
Catcher()
static CoroutineCatcher JUtils.Coroutines.Catcher (IEnumerator coroutine) static
Returns a CoroutineCatcher
Run()
static Coroutine JUtils.Coroutines.Run (IEnumerator routine) inline static
Run a routine on the JUtils Object – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
Definition at line 100 of file Coroutines.cs.
         {
             return JUtilsObject.Instance.StartCoroutine(routine);
         }
References JUtils.Internal.JUtilsObject.Instance.
RunDelay() [1/2]
static Coroutine JUtils.Coroutines.RunDelay (float delay, Action action) inline static
Run a action after a certain amount of seconds; – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
Definition at line 80 of file Coroutines.cs.
         {
             return JUtilsObject.Instance.StartCoroutine(Routines.DelayRoutine(delay, action));
         }
References JUtils.Routines.DelayRoutine(), and JUtils.Internal.JUtilsObject.Instance.
RunDelay() [2/2]
static Coroutine JUtils.Coroutines.RunDelay (TimeSpan delay, Action action) inline static
Run a action after a certain amount of seconds – You should always use StartCoroutine instead of the Coroutines, but this can be more useful.
Definition at line 90 of file Coroutines.cs.
         {
             return JUtilsObject.Instance.StartCoroutine(Routines.DelayRoutine(delay, action));
         }
References JUtils.Routines.DelayRoutine(), and JUtils.Internal.JUtilsObject.Instance.
RunNextFrame()
static Coroutine JUtils.Coroutines.RunNextFrame (Action action) inline static
Run a action in the next frame
Definition at line 70 of file Coroutines.cs.
         {
             return JUtilsObject.Instance.StartCoroutine(Routines.NextFrameRoutine(action));
         }
References JUtils.Internal.JUtilsObject.Instance, and JUtils.Routines.NextFrameRoutine().
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState().
WaitForEndOfFrame()
static WaitForEndOfFrame JUtils.Coroutines.WaitForEndOfFrame () static
Return the cached WaitForFixedUpdate instance
WaitForFixedUpdate()
static WaitForFixedUpdate JUtils.Coroutines.WaitForFixedUpdate () static
Return the cached WaitForFixedUpdate instance
WaitForSeconds()
static WaitForSeconds JUtils.Coroutines.WaitForSeconds (float seconds) inline static
Faster alternative to WaitForSeconds, caches the object. This will permanently cache the instance unless removed with Coroutines.wfsDictionary
Definition at line 29 of file Coroutines.cs.
         {
             Dictionary<float, WaitForSeconds> dict = wfsDictionary;
             if (wfsDictionary.ContainsKey(seconds)) return dict[seconds];
             return dict[seconds] = new WaitForSeconds(seconds);
         }
References JUtils.Coroutines.wfsDictionary.
WaitForSecondsRealtime()
static WaitForSecondsRealtime JUtils.Coroutines.WaitForSecondsRealtime (float seconds) inline static
Faster alternative to creating a new WaitForSecondsRealtime, caches the object. This will permanently cache the instance unless removed with Coroutines.wfsRtDictionary
Definition at line 41 of file Coroutines.cs.
         {
             Dictionary<float, WaitForSecondsRealtime> dict = wfsRtDictionary;
             if (wfsDictionary.ContainsKey(seconds)) return dict[seconds];
             return dict[seconds] = new WaitForSecondsRealtime(seconds);
         }
References JUtils.Coroutines.wfsDictionary, and JUtils.Coroutines.wfsRtDictionary.
Member Data Documentation
_waitForEndOfFrame
WaitForEndOfFrame JUtils.Coroutines._waitForEndOfFrame static private
Definition at line 22 of file Coroutines.cs.
_waitForFixedUpdate
WaitForFixedUpdate JUtils.Coroutines._waitForFixedUpdate static private
Definition at line 21 of file Coroutines.cs.
_wfsDictionary
Dictionary<float, WaitForSeconds> JUtils.Coroutines._wfsDictionary static private
Definition at line 13 of file Coroutines.cs.
_wfsRtDictionary
Dictionary<float, WaitForSecondsRealtime> JUtils.Coroutines._wfsRtDictionary static private
Definition at line 17 of file Coroutines.cs.
Property Documentation
wfsDictionary
Dictionary<float, WaitForSeconds> JUtils.Coroutines.wfsDictionary static get
Definition at line 14 of file Coroutines.cs.
Referenced by JUtils.Coroutines.WaitForSeconds(), and JUtils.Coroutines.WaitForSecondsRealtime().
wfsRtDictionary
Dictionary<float, WaitForSecondsRealtime> JUtils.Coroutines.wfsRtDictionary static get
Definition at line 18 of file Coroutines.cs.
Referenced by JUtils.Coroutines.WaitForSecondsRealtime().
The documentation for this class was generated from the following file:
JUtils/Misc/Coroutines.cs