JUrils: JUtils.Components.HealthComponent Class Reference
JUtils.Components.HealthComponent Class Reference
Public Member Functions
int Damage (int amount)
Damage the component
int Heal (int amount)
Heal the component
int Damage (IDamageEvent @event)
Damage the component
int Heal (IHealEvent @event)
Heal the component
void Kill ()
Public Attributes
bool isDead
Properties
int maxHealth [get]
int health [get]
Private Member Functions
void OnEnable ()
int ChangeHealth (int amount)
Private Attributes
int _health
int _maxHealth
Detailed Description
Definition at line 9 of file HealthComponent.cs.
Member Function Documentation
ChangeHealth()
int JUtils.Components.HealthComponent.ChangeHealth (int amount) inline private
Parameters
amount
Returns
true when died, other param is the damage done
Definition at line 101 of file HealthComponent.cs.
         {
             if (isDead) return 0;
             //  Setting the health based on the changed amount
             int newHealth = Mathf.Clamp(_health + amount, 0, _maxHealth);
             int changed   = newHealth - _health;
             _health       = newHealth;
             //  Running events
             if (_health == 0) {
                 isDead = true;
                 SendMessage("OnDeath", SendMessageOptions.DontRequireReceiver);
             }
             //  Sending general HealthChange event
             SendMessage("HealthChange", changed, SendMessageOptions.DontRequireReceiver);
             //  Returning changed amount
             return changed;
         }
References JUtils.Components.HealthComponent._health, JUtils.Components.HealthComponent._maxHealth, and JUtils.Components.HealthComponent.isDead.
Referenced by JUtils.Components.HealthComponent.Damage(), JUtils.Components.HealthComponent.Heal(), and JUtils.Components.HealthComponent.Kill().
Damage() [1/2]
int JUtils.Components.HealthComponent.Damage (IDamageEvent @ event) inline
Damage the component
Definition at line 65 of file HealthComponent.cs.
         {
             int amount = @event.damage;
             if (amount < 0) throw new ArgumentException("Amount must not be lower than one");
             int changed = -ChangeHealth(-amount);
             @event.damage = changed;
             if (changed > 0) SendMessage("OnDamage", @event, SendMessageOptions.DontRequireReceiver);
             return changed;
         }
References JUtils.Components.HealthComponent.ChangeHealth().
Damage() [2/2]
int JUtils.Components.HealthComponent.Damage (int amount) inline
Damage the component
Definition at line 33 of file HealthComponent.cs.
         {
             if (amount < 0) throw new ArgumentException("Amount must not be lower than one");
             int changed = -ChangeHealth(-amount);
             IDamageEvent evt = new SimpleDamageEvent() { damage = changed};
             if (changed > 0) SendMessage("OnDamage", evt, SendMessageOptions.DontRequireReceiver);
             return changed;
         }
References JUtils.Components.HealthComponent.ChangeHealth().
Heal() [1/2]
int JUtils.Components.HealthComponent.Heal (IHealEvent @ event) inline
Heal the component
Definition at line 82 of file HealthComponent.cs.
         {
             int amount = @event.amount;
             if (amount < 1) throw new ArgumentException("Amount must not be lower than one");
             int changed = ChangeHealth(amount);
             @event.amount = changed;
             if (changed > 0) SendMessage("OnHeal", @event, SendMessageOptions.DontRequireReceiver);
             return changed;
         }
References JUtils.Components.HealthComponent.ChangeHealth().
Heal() [2/2]
int JUtils.Components.HealthComponent.Heal (int amount) inline
Heal the component
Definition at line 49 of file HealthComponent.cs.
         {
             if (amount < 1) throw new ArgumentException("Amount must not be lower than one");
             int changed = ChangeHealth(amount);
             IHealEvent evt = new SimpleHealEvent() { amount = changed};
             if (changed > 0) SendMessage("OnHeal", evt, SendMessageOptions.DontRequireReceiver);
             return changed;
         }
References JUtils.Components.HealthComponent.ChangeHealth().
Kill()
void JUtils.Components.HealthComponent.Kill () inline
Kill the unit
Definition at line 132 of file HealthComponent.cs.
         {
             if (isDead) return;
             ChangeHealth(-_maxHealth * 10000);
         }
References JUtils.Components.HealthComponent._maxHealth, JUtils.Components.HealthComponent.ChangeHealth(), and JUtils.Components.HealthComponent.isDead.
OnEnable()
void JUtils.Components.HealthComponent.OnEnable () inline private
Reset death & health
Definition at line 23 of file HealthComponent.cs.
         {
             isDead = false;
             _health = _maxHealth;
         }
References JUtils.Components.HealthComponent._health, JUtils.Components.HealthComponent._maxHealth, and JUtils.Components.HealthComponent.isDead.
Member Data Documentation
_health
int JUtils.Components.HealthComponent._health private
Definition at line 11 of file HealthComponent.cs.
Referenced by JUtils.Components.HealthComponent.ChangeHealth(), and JUtils.Components.HealthComponent.OnEnable().
_maxHealth
int JUtils.Components.HealthComponent._maxHealth private
Definition at line 12 of file HealthComponent.cs.
Referenced by JUtils.Components.HealthComponent.ChangeHealth(), JUtils.Components.HealthComponent.Kill(), and JUtils.Components.HealthComponent.OnEnable().
isDead
bool JUtils.Components.HealthComponent.isDead
Definition at line 14 of file HealthComponent.cs.
Referenced by JUtils.Components.HealthComponent.ChangeHealth(), JUtils.Components.HealthComponent.Kill(), and JUtils.Components.HealthComponent.OnEnable().
Property Documentation
health
int JUtils.Components.HealthComponent.health get
Definition at line 17 of file HealthComponent.cs.
maxHealth
int JUtils.Components.HealthComponent.maxHealth get
Definition at line 16 of file HealthComponent.cs.
The documentation for this class was generated from the following file:
JUtils/Components/HealthComponent/HealthComponent.cs