JUtils: JUtils.Components.ObjectPool Class Reference
JUtils.Components.ObjectPool Class Reference
Public Member Functions
PoolItem SpawnItem ()
PoolItem SpawnItem (Vector3 localPosition)
PoolItem SpawnItem (Vector3 localPosition, Transform parent)
PoolItem SpawnItem (Transform parent)
PoolItem SpawnItem (Vector3 localPosition, Quaternion localRotation, Transform parent=null)
bool TryGetItem (out PoolItem item)
int AddItems (int amount=-1)
Package Functions
bool ReturnItem (PoolItem item)
Private Member Functions
void Awake ()
void Start ()
Private Attributes
PoolItem template
int prefill = 10
int maxSize = -1
bool autoExpand = true
int autoExpandAmount = 5
PoolItem[] poolItems
Queue< PoolItem > freeItems
Detailed Description
Definition at line 12 of file ObjectPool.cs.
Member Function Documentation
AddItems()
int JUtils.Components.ObjectPool.AddItems (int amount = -1) inline
Definition at line 62 of file ObjectPool.cs.
         {
             if (amount <= 0) amount = autoExpandAmount;
             int newSize = maxSize > 0 ? Mathf.Max(poolItems.Length, amount + poolItems.Length) : amount + poolItems.Length;
             amount = newSize - poolItems.Length;
             if (newSize == poolItems.Length) {
                 return 0;
             }
             Array.Resize(ref poolItems, newSize);
             while (amount --> 0) {
                 PoolItem item = Instantiate(template, Vector3.zero, Quaternion.identity, transform);
                 item.ObjectPool = this;
                 item.gameObject.SetActive(false);
                 poolItems[newSize - amount - 1] = item;
                 freeItems.Enqueue(item);
             }
             return amount;
         }
References JUtils.Components.ObjectPool.autoExpandAmount, JUtils.Components.ObjectPool.freeItems, JUtils.Components.ObjectPool.maxSize, JUtils.Components.PoolItem.ObjectPool, and JUtils.Components.ObjectPool.poolItems.
Referenced by JUtils.Components.ObjectPool.Start(), and JUtils.Components.ObjectPool.TryGetItem().
Awake()
void JUtils.Components.ObjectPool.Awake () inline private
Definition at line 104 of file ObjectPool.cs.
         {
             if (template == null) {
                 Debug.LogError("No template has been set!", this);
                 return;
             }
             if (template.transform.parent != transform) return;
             template.gameObject.SetActive(false);
             template.ObjectPool = this;
         }
ReturnItem()
bool JUtils.Components.ObjectPool.ReturnItem (PoolItem item) inline package
Definition at line 86 of file ObjectPool.cs.
         {
             if (!poolItems.Contains(item) || freeItems.Contains(item)) {
                 return false;
             }
             item.Despawn();
             Transform transform = item.transform;
             transform.parent        = this.transform;
             transform.localPosition = Vector3.zero;
             transform.localRotation = Quaternion.identity;
             freeItems.Enqueue(item);
             return true;
         }
References JUtils.Components.PoolItem.Despawn(), JUtils.Components.ObjectPool.freeItems, and JUtils.Components.ObjectPool.poolItems.
Referenced by JUtils.Components.PoolItem.ReturnToPool().
SpawnItem() [1/5]
PoolItem JUtils.Components.ObjectPool.SpawnItem () inline
Definition at line 25 of file ObjectPool.cs.
         {
             return SpawnItem(Vector3.zero, Quaternion.identity);
         }
SpawnItem() [2/5]
PoolItem JUtils.Components.ObjectPool.SpawnItem (Transform parent)
SpawnItem() [3/5]
PoolItem JUtils.Components.ObjectPool.SpawnItem (Vector3 localPosition)
SpawnItem() [4/5]
PoolItem JUtils.Components.ObjectPool.SpawnItem (Vector3 localPosition, Quaternion localRotation, Transform parent = null) inline
Definition at line 34 of file ObjectPool.cs.
         {
             if (!TryGetItem(out PoolItem item)) return null;
             Transform transform = item.transform;
             transform.parent        = parent;
             transform.localPosition = localPosition;
             transform.rotation      = localRotation;
             return item;
         }
References JUtils.Components.ObjectPool.TryGetItem().
SpawnItem() [5/5]
PoolItem JUtils.Components.ObjectPool.SpawnItem (Vector3 localPosition, Transform parent)
Start()
void JUtils.Components.ObjectPool.Start () inline private
Definition at line 118 of file ObjectPool.cs.
         {
             if (!template) return;
             poolItems = Array.Empty<PoolItem>();
             freeItems = new Queue<PoolItem>();
             AddItems(prefill);
         }
References JUtils.Components.ObjectPool.AddItems(), JUtils.Components.ObjectPool.freeItems, JUtils.Components.ObjectPool.poolItems, and JUtils.Components.ObjectPool.prefill.
TryGetItem()
bool JUtils.Components.ObjectPool.TryGetItem (out PoolItem item) inline
Definition at line 47 of file ObjectPool.cs.
         {
             if (freeItems.Count == 0 && (!autoExpand || AddItems() <= 0)) {
                 Debug.LogWarning("Tried to get item from empty pool");
                 item = null;
                 return false;
             }
             item = freeItems.Dequeue();
             item.Spawn();
             return true;
         }
References JUtils.Components.ObjectPool.AddItems(), JUtils.Components.ObjectPool.autoExpand, and JUtils.Components.ObjectPool.freeItems.
Referenced by JUtils.Components.ObjectPool.SpawnItem().
Member Data Documentation
autoExpand
bool JUtils.Components.ObjectPool.autoExpand = true private
Definition at line 18 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.TryGetItem().
autoExpandAmount
int JUtils.Components.ObjectPool.autoExpandAmount = 5 private
Definition at line 19 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.AddItems().
freeItems
Queue<PoolItem> JUtils.Components.ObjectPool.freeItems private
Definition at line 22 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.AddItems(), JUtils.Components.ObjectPool.ReturnItem(), JUtils.Components.ObjectPool.Start(), and JUtils.Components.ObjectPool.TryGetItem().
maxSize
int JUtils.Components.ObjectPool.maxSize = -1 private
Definition at line 16 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.AddItems().
poolItems
PoolItem [] JUtils.Components.ObjectPool.poolItems private
Definition at line 21 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.AddItems(), JUtils.Components.ObjectPool.ReturnItem(), and JUtils.Components.ObjectPool.Start().
prefill
int JUtils.Components.ObjectPool.prefill = 10 private
Definition at line 15 of file ObjectPool.cs.
Referenced by JUtils.Components.ObjectPool.Start().
template
PoolItem JUtils.Components.ObjectPool.template private
Definition at line 14 of file ObjectPool.cs.
The documentation for this class was generated from the following file:
JUtils/Components/ObjectPool.cs