JUtils: JUtils.ServiceManager Class Reference
JUtils.ServiceManager Class Reference
A simple service manager
Static Public Member Functions
static bool Exists< T > ()
Check if a service exists
static bool Exists (Type serviceType)
Check if a service exists
static T Get< T > ()
Get the instance of the given service
static IService Get (Type serviceType)
Get the instance of the given service
static void Register (Type serviceType, IService service)
Register a new service and initialize it. Will throw if it already exists.
static void Remove< T > ()
Remove an existing service and dispose it
static void Remove (Type type)
Remove an existing service and dispose it
Additional Inherited Members
Protected Member Functions inherited from JUtils.AutoSingletonBehaviour< ServiceManager >
virtual void Awake ()
virtual void OnDestroy ()
Properties inherited from JUtils.AutoSingletonBehaviour< ServiceManager >
static T instance [get]
static bool exists [get]
Detailed Description
A simple service manager
Member Function Documentation
Exists()
static bool JUtils.ServiceManager.Exists (Type serviceType) inline static
Check if a service exists
References JUtils.AutoSingletonBehaviour< ServiceManager >.instance.
Exists< T >()
static bool JUtils.ServiceManager.Exists< T > () inline static
Check if a service exists
Type Constraints
T : IService
References JUtils.AutoSingletonBehaviour< ServiceManager >.instance.
Get()
static IService JUtils.ServiceManager.Get (Type serviceType) inline static
Get the instance of the given service
References JUtils.AutoSingletonBehaviour< ServiceManager >.instance.
Get< T >()
static T JUtils.ServiceManager.Get< T > () inline static
Get the instance of the given service
Type Constraints
T : IService
References JUtils.ServiceManager.Get().
Register()
static void JUtils.ServiceManager.Register (Type serviceType, IService service) inline static
Register a new service and initialize it. Will throw if it already exists.
References JUtils.AssemblyJUtils.ExtendsClassOrInterface(), JUtils.IService.Init(), and JUtils.AutoSingletonBehaviour< ServiceManager >.instance.
Remove()
static void JUtils.ServiceManager.Remove (Type type) inline static
Remove an existing service and dispose it
References JUtils.IService.Dispose(), JUtils.ServiceManager.Get(), and JUtils.AutoSingletonBehaviour< ServiceManager >.instance.
Remove< T >()
static void JUtils.ServiceManager.Remove< T > () inline static
Remove an existing service and dispose it
Type Constraints
T : IService
References JUtils.ServiceManager.Remove().
The documentation for this class was generated from the following file:
ServiceManager.cs