JUtils: JUtils.FSM.StateData Class Reference
JUtils.FSM.StateData Class Reference
Public Member Functions
StateData (params object[] arguments)
T Get< T > (int index)
Get an argument at an index
bool TryGet< T > (int index, out T argument)
Try get the argument at an index
bool Has (int index)
See if the index exists
bool Has< T > (int index)
See if the index exists, and if its of the same type
Public Attributes
readonly object[] Arguments
Detailed Description
Definition at line 7 of file StateData.cs.
Constructor & Destructor Documentation
StateData()
JUtils.FSM.StateData.StateData (params object[] arguments) inline
Definition at line 12 of file StateData.cs.
         {
             Arguments = arguments;
         }
References JUtils.FSM.StateData.Arguments.
Member Function Documentation
Get< T >()
T JUtils.FSM.StateData.Get< T > (int index) inline
Get an argument at an index
Definition at line 21 of file StateData.cs.
         {
             if (!Has(index))
                 throw new ArgumentOutOfRangeException();
             object obj = Arguments[index];
             if (obj is not T argument)
                 throw new ArgumentException($"Type '{obj.GetType().Name}' is not castable to '{typeof(T).Name}'");
             return argument;
         }
References JUtils.FSM.StateData.Arguments, and JUtils.FSM.StateData.Has().
Has()
bool JUtils.FSM.StateData.Has (int index) inline
See if the index exists
Definition at line 54 of file StateData.cs.
         {
             return index < Arguments.Length;
         }
References JUtils.FSM.StateData.Arguments.
Referenced by JUtils.FSM.StateData.Get< T >(), and JUtils.FSM.StateData.TryGet< T >().
Has< T >()
bool JUtils.FSM.StateData.Has< T > (int index) inline
See if the index exists, and if its of the same type
Definition at line 63 of file StateData.cs.
         {
             return index < Arguments.Length && Arguments[index] is T;
         }
References JUtils.FSM.StateData.Arguments.
TryGet< T >()
bool JUtils.FSM.StateData.TryGet< T > (int index, out T argument) inline
Try get the argument at an index
Definition at line 38 of file StateData.cs.
         {
             argument = default;
             if (!Has(index)) return false;
             object obj = Arguments[index];
             if (obj is not T obj1) return false;
             argument = obj1;
             return true;
         }
References JUtils.FSM.StateData.Arguments, and JUtils.FSM.StateData.Has().
Member Data Documentation
Arguments
readonly object [] JUtils.FSM.StateData.Arguments
Definition at line 9 of file StateData.cs.
Referenced by JUtils.FSM.StateData.Get< T >(), JUtils.FSM.StateData.Has(), JUtils.FSM.StateData.Has< T >(), JUtils.FSM.StateData.StateData(), and JUtils.FSM.StateData.TryGet< T >().
The documentation for this class was generated from the following file:
JUtils/FSM/StateData.cs