JUrils: JUtils.Singletons.SingletonManager Class Reference
JUtils.Singletons.SingletonManager Class Reference
Centralized singleton to fix reference & hot reload issues issues
Static Public Member Functions
static T GetSingleton< T > ()
Get a singleton from this class
static bool SetSingleton< T > (ISingleton< T > singleton)
Set a singleton reference
static bool RemoveSingleton< T > (ISingleton< T > singleton)
Remove a singleton from all lists
Properties
static SingletonManager Instance [get]
Private Attributes
List< MonoBehaviour > _singletons = new ()
Detailed Description
Centralized singleton to fix reference & hot reload issues issues
Definition at line 15 of file SingletonManager.cs.
Member Function Documentation
GetSingleton< T >()
static T JUtils.Singletons.SingletonManager.GetSingleton< T > () inline static
Get a singleton from this class
Type Constraints
T : MonoBehaviour
T : ISingleton<T>
Definition at line 23 of file SingletonManager.cs.
                                                   : MonoBehaviour, ISingleton<T>
         {
             return Instance._singletons.FirstOrDefault(x => x is T) as T;
         }
References JUtils.Singletons.SingletonManager._singletons, and JUtils.Singletons.SingletonManager.Instance.
RemoveSingleton< T >()
static bool JUtils.Singletons.SingletonManager.RemoveSingleton< T > (ISingleton< T > singleton) inline static
Remove a singleton from all lists
Type Constraints
T : MonoBehaviour
T : ISingleton<T>
Definition at line 48 of file SingletonManager.cs.
                                                                                : MonoBehaviour, ISingleton<T>
         {
            return Instance._singletons.Remove(singleton as MonoBehaviour);
         }
References JUtils.Singletons.SingletonManager._singletons, and JUtils.Singletons.SingletonManager.Instance.
SetSingleton< T >()
static bool JUtils.Singletons.SingletonManager.SetSingleton< T > (ISingleton< T > singleton) inline static
Set a singleton reference
Type Constraints
T : MonoBehaviour
T : ISingleton<T>
Definition at line 32 of file SingletonManager.cs.
                                                                             : MonoBehaviour, ISingleton<T>
         {
            SingletonManager manager = Instance;
            if (manager._singletons.Any(x => x is T)) {
                return false;
            }
            manager._singletons.Add(singleton as MonoBehaviour);
            return true;
         }
References JUtils.Singletons.SingletonManager._singletons, and JUtils.Singletons.SingletonManager.Instance.
Member Data Documentation
_singletons
List<MonoBehaviour> JUtils.Singletons.SingletonManager._singletons = new () private
Definition at line 55 of file SingletonManager.cs.
Referenced by JUtils.Singletons.SingletonManager.GetSingleton< T >(), JUtils.Singletons.SingletonManager.RemoveSingleton< T >(), and JUtils.Singletons.SingletonManager.SetSingleton< T >().
Property Documentation
Instance
SingletonManager JUtils.Singletons.SingletonManager.Instance static get
Definition at line 17 of file SingletonManager.cs.
Referenced by JUtils.Singletons.SingletonManager.GetSingleton< T >(), JUtils.Singletons.SingletonManager.RemoveSingleton< T >(), and JUtils.Singletons.SingletonManager.SetSingleton< T >().
The documentation for this class was generated from the following file:
JUtils/Singletons/SingletonManager.cs