JUrils: JUtils.FSM.State< T1, T2, T3 > Class Template Reference
JUtils.FSM.State< T1, T2, T3 > Class Template Reference abstract
Protected Member Functions
void Deactivate ()
abstract void OnActivate ()
abstract void OnDeactivate ()
StateRef< T > Ref< T > ()
virtual void ActiveUpdate ()
virtual void Awake ()
virtual void Update ()
override void OnActivate ()
abstract void OnActivate (T a)
override void OnActivate ()
abstract void OnActivate (T1 a, T2 b)
override void OnActivate ()
abstract void OnActivate (T1 a, T2 b, T3 c)
Package Functions
void ActivateState ()
void DeactivateState ()
Properties
bool IsActive [get, private set]
float TimeInState [get]
float UnscaledTimeInState [get]
StateMachine StateMachine [get, set]
StateData Data [get, set]
Events
Action< State > OnStateActivate
Action< State > OnStateDeactivate
Private Attributes
bool setEnabledBasedOnActive = true
float _timeEnteredState
float _unscaledTimeEnteredState
Detailed Description
Definition at line 124 of file State.cs.
Member Function Documentation
ActivateState()
void JUtils.FSM.State< T1, T2, T3 >.ActivateState () inline package
Definition at line 26 of file State.cs.
         {
             try {
                 _timeEnteredState         = Time.time;
                 _unscaledTimeEnteredState = Time.unscaledTime;
                 gameObject.SetActive(true);
                 IsActive = true;
                 OnActivate();
                 OnStateActivate?.Invoke(this);
             }
             catch (Exception e) {
                 Debug.LogException(e);
                 Coroutines.RunNextFrame(Deactivate); // Run next frame to avoid stack overflow exceptions
             }
         }
References JUtils.FSM.State< T1, T2, T3 >._timeEnteredState, JUtils.FSM.State< T1, T2, T3 >._unscaledTimeEnteredState, JUtils.FSM.State< T1, T2, T3 >.Deactivate(), JUtils.FSM.State< T1, T2, T3 >.IsActive, JUtils.FSM.State< T1, T2, T3 >.OnActivate(), JUtils.FSM.State< T1, T2, T3 >.OnStateActivate, and JUtils.Coroutines.RunNextFrame().
Referenced by JUtils.FSM.StateMachine.ContinueQueue(), and JUtils.FSM.StateMachine.Start().
ActiveUpdate()
virtual void JUtils.FSM.State< T1, T2, T3 >.ActiveUpdate () inline protected virtual
Definition at line 76 of file State.cs.
         {
         }
Referenced by JUtils.FSM.State< T1, T2, T3 >.Update().
Awake()
virtual void JUtils.FSM.State< T1, T2, T3 >.Awake () inline protected virtual
Reimplemented in JUtils.FSM.StateMachine.
Definition at line 81 of file State.cs.
         {
             if (!IsActive && setEnabledBasedOnActive) gameObject.SetActive(false);
         }
References JUtils.FSM.State< T1, T2, T3 >.IsActive, and JUtils.FSM.State< T1, T2, T3 >.setEnabledBasedOnActive.
Deactivate()
void JUtils.FSM.State< T1, T2, T3 >.Deactivate () inline protected
Definition at line 61 of file State.cs.
         {
             if (!IsActive) return;
             StateMachine.ContinueQueue();
         }
References JUtils.FSM.StateMachine.ContinueQueue(), and JUtils.FSM.State< T1, T2, T3 >.IsActive.
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState().
DeactivateState()
void JUtils.FSM.State< T1, T2, T3 >.DeactivateState () inline package
Definition at line 44 of file State.cs.
         {
             try {
                 if (setEnabledBasedOnActive) {
                     gameObject.SetActive(false);
                 }
                 IsActive = false;
                 OnDeactivate();
                 OnStateDeactivate?.Invoke(this);
             }
             catch (Exception e) {
                 Debug.LogException(e);
             }
         }
References JUtils.FSM.State< T1, T2, T3 >.IsActive, JUtils.FSM.State< T1, T2, T3 >.OnDeactivate(), JUtils.FSM.State< T1, T2, T3 >.OnStateDeactivate, and JUtils.FSM.State< T1, T2, T3 >.setEnabledBasedOnActive.
Referenced by JUtils.FSM.StateMachine.ContinueQueue(), and JUtils.FSM.StateMachine.OnDeactivate().
OnActivate() [1/7]
abstract void JUtils.FSM.State< T1, T2, T3 >.OnActivate () protected pure virtual
Implemented in JUtils.FSM.StateMachine.
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState(), and JUtils.FSM.State< T1, T2, T3 >.OnActivate().
OnActivate() [2/7]
override void JUtils.FSM.State< T1, T2, T3 >.OnActivate () inline protected
Definition at line 97 of file State.cs.
         {
             T a = Data.Get<T>(0);
             OnActivate(a);
         }
References JUtils.FSM.State< T1, T2, T3 >.Data, and JUtils.FSM.State< T1, T2, T3 >.OnActivate().
OnActivate() [3/7]
override void JUtils.FSM.State< T1, T2, T3 >.OnActivate () inline protected
Definition at line 111 of file State.cs.
         {
             T1 a = Data.Get<T1>(0);
             T2 b = Data.Get<T2>(0);
             OnActivate(a, b);
         }
References JUtils.FSM.State< T1, T2, T3 >.Data, and JUtils.FSM.State< T1, T2, T3 >.OnActivate().
OnActivate() [4/7]
override void JUtils.FSM.State< T1, T2, T3 >.OnActivate () inline protected
Definition at line 126 of file State.cs.
         {
             T1 a = Data.Get<T1>(0);
             T2 b = Data.Get<T2>(0);
             T3 c = Data.Get<T3>(0);
             OnActivate(a, b, c);
         }
References JUtils.FSM.State< T1, T2, T3 >.Data, and JUtils.FSM.State< T1, T2, T3 >.OnActivate().
OnActivate() [5/7]
abstract void JUtils.FSM.State< T1, T2, T3 >.OnActivate (T a) protected pure virtual
OnActivate() [6/7]
abstract void JUtils.FSM.State< T1, T2, T3 >.OnActivate (T1 a, T2 b) protected pure virtual
OnActivate() [7/7]
abstract void JUtils.FSM.State< T1, T2, T3 >.OnActivate (T1 a, T2 b, T3 c) protected pure virtual
OnDeactivate()
abstract void JUtils.FSM.State< T1, T2, T3 >.OnDeactivate () protected pure virtual
Implemented in JUtils.FSM.StateMachine.
Referenced by JUtils.FSM.State< T1, T2, T3 >.DeactivateState().
Ref< T >()
StateRef<T> JUtils.FSM.State< T1, T2, T3 >.Ref< T > () protected
Type Constraints
T : State
T : new
Update()
virtual void JUtils.FSM.State< T1, T2, T3 >.Update () inline protected virtual
Definition at line 87 of file State.cs.
         {
             if (IsActive) ActiveUpdate();
         }
References JUtils.FSM.State< T1, T2, T3 >.ActiveUpdate(), and JUtils.FSM.State< T1, T2, T3 >.IsActive.
Member Data Documentation
_timeEnteredState
float JUtils.FSM.State< T1, T2, T3 >._timeEnteredState private
Definition at line 23 of file State.cs.
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState().
_unscaledTimeEnteredState
float JUtils.FSM.State< T1, T2, T3 >._unscaledTimeEnteredState private
Definition at line 24 of file State.cs.
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState().
setEnabledBasedOnActive
bool JUtils.FSM.State< T1, T2, T3 >.setEnabledBasedOnActive = true private
Definition at line 12 of file State.cs.
Referenced by JUtils.FSM.State< T1, T2, T3 >.Awake(), and JUtils.FSM.State< T1, T2, T3 >.DeactivateState().
Property Documentation
Data
StateData JUtils.FSM.State< T1, T2, T3 >.Data get set
Definition at line 21 of file State.cs.
 { get; internal set; }
Referenced by JUtils.FSM.StateMachine.AddToQueue(), JUtils.FSM.StateMachine.ContinueQueue(), and JUtils.FSM.State< T1, T2, T3 >.OnActivate().
IsActive
bool JUtils.FSM.State< T1, T2, T3 >.IsActive get private set
Definition at line 17 of file State.cs.
 { get; private set; }
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState(), JUtils.FSM.State< T1, T2, T3 >.Awake(), JUtils.FSM.StateMachine.ContinueQueue(), JUtils.FSM.State< T1, T2, T3 >.Deactivate(), JUtils.FSM.State< T1, T2, T3 >.DeactivateState(), and JUtils.FSM.State< T1, T2, T3 >.Update().
StateMachine
StateMachine JUtils.FSM.State< T1, T2, T3 >.StateMachine get set
Definition at line 20 of file State.cs.
 { get; internal set; }
Referenced by JUtils.FSM.StateMachine.ContinueQueue().
TimeInState
float JUtils.FSM.State< T1, T2, T3 >.TimeInState get
Definition at line 18 of file State.cs.
UnscaledTimeInState
float JUtils.FSM.State< T1, T2, T3 >.UnscaledTimeInState get
Definition at line 19 of file State.cs.
Event Documentation
OnStateActivate
Action<State> JUtils.FSM.State< T1, T2, T3 >.OnStateActivate
Definition at line 14 of file State.cs.
Referenced by JUtils.FSM.State< T1, T2, T3 >.ActivateState().
OnStateDeactivate
Action<State> JUtils.FSM.State< T1, T2, T3 >.OnStateDeactivate
Definition at line 15 of file State.cs.
Referenced by JUtils.FSM.State< T1, T2, T3 >.DeactivateState().
The documentation for this class was generated from the following file:
JUtils/FSM/State.cs