JUtils: JUtils.StateMachine Class Reference
JUtils.StateMachine Class Reference abstract
A mono behaviour state-machine that can also be used as a state
Classes
struct QueueEntry
Representation of the state and its data in the queue
Public Member Functions
void GoToState ([NotNull] State state, [CanBeNull] StateData data)
Queues the current given state, then goes to it
void GoToState< T > ([CanBeNull] StateData data)
Clears the StateQueue and goes to the given state
void AddToQueue ([NotNull] State state, [CanBeNull] StateData data, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T > ([CanBeNull] StateData data, bool queueFirst=false)
Adds a new state to the queue
void ClearQueue ()
Clears all states in the queue
void ContinueQueue ()
Deactivate the current state and go to the next one
T FindState< T > ()
Find a state within the child objects of this state-machine, if _autoCreateStates is enabled, it will automatically instantiate the state
bool TryFindState< T > (out T state)
Try finding a state within the child objects of this state-machine, if _autoCreateStates is enabled, it will automatically instantiate that state
void Activate ([CanBeNull] StateData data=null)
Activates the state machine
new void Deactivate ()
Continues the queue in the state machine, or deactivates the state if it is the root state machine
void GoToState (State state)
Clears the StateQueue and goes to the given state
void GoToState< T, T1 > (T state, T1 arg1)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2 > (T state, T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
void GoToState< T > ()
Adds a new state to the queue
void GoToState< T, T1 > (T1 arg1)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2 > (T1 arg1, T2 arg2)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3)
Clears the StateQueue and goes to the given state
void GoToState< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3)
Adds a new state to the queue
void GoToState< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2)
Adds a new state to the queue
void GoToState< T, T1 > (StateRef< T > stateRef, T1 arg1)
Adds a new state to the queue
void GoToState< T > (StateRef< T > stateRef)
Adds a new state to the queue
void AddToQueue< T > (T state, bool queueFist=false)
Adds a new state to the queue
void AddToQueue< T, T1 > (T state, T1 arg1, bool queueFist=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (T state, T1 arg1, T2 arg2, bool queueFist=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T > (bool queueFist=false)
Adds a new state to the queue
void AddToQueue< T, T1 > (T1 arg1, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (T1 arg1, T2 arg2, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T, T1 > (StateRef< T > stateRef, T1 arg1, bool queueFirst=false)
Adds a new state to the queue
void AddToQueue< T > (StateRef< T > stateRef, bool queueFirst=false)
Adds a new state to the queue
Protected Member Functions
abstract void OnNoState ()
Gets called when there is no next state in the queue
override void Awake ()
virtual void Start ()
virtual void Reset ()
virtual void OnValidate ()
Protected Member Functions inherited from JUtils.State< T1, T2, T3 >
void Deactivate ()
Deactivate this state and make the state-machine continue its queue
abstract void OnActivate ()
Gets called when the state activates
abstract void OnDeactivate ()
Gets called when the sate deactivates
StateRef< T > Ref< T > ()
Used for making typed argument adding to states prettier
virtual void ActiveUpdate ()
Only runs the Update() function when the state is active
virtual void Update ()
override void OnActivate ()
abstract void OnActivate (T param)
override void OnActivate ()
abstract void OnActivate (T1 param1, T2 param2)
override void OnActivate ()
abstract void OnActivate (T1 param1, T2 param2, T3 param3)
Protected Attributes
State currentState
List< QueueEntry > stateQueue = new()
Properties
bool hasActiveState [get]
bool isQueueFilled [get]
bool isQueueEmpty [get]
Properties inherited from JUtils.State< T1, T2, T3 >
bool isActive [get]
StateMachine stateMachine [get, set]
float timeInState [get]
Get the amount of seconds that this state is active. Returns 0 if the state is not active
float unscaledTimeInState [get]
Get the amount of unscaled seconds that this state is active. Returns 0 if the state is not active
StateData stateData [get]
Events
Action< State > onStateChanged
Events inherited from JUtils.State< T1, T2, T3 >
Action< State > onStateActivate
Action< State > onStateDeactivate
Detailed Description
A mono behaviour state-machine that can also be used as a state
Member Function Documentation
Activate()
void JUtils.StateMachine.Activate ([CanBeNull] StateData data = null) inline
Activates the state machine
References JUtils.State< T1, T2, T3 >.isActive.
AddToQueue()
void JUtils.StateMachine.AddToQueue ([NotNull] State state, [CanBeNull] StateData data, bool queueFirst = false) inline
Adds a new state to the queue
AddToQueue< T >() [1/4]
void JUtils.StateMachine.AddToQueue< T > ([CanBeNull] StateData data, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
References JUtils.StateMachine.AddToQueue().
AddToQueue< T >() [2/4]
void JUtils.StateMachine.AddToQueue< T > (bool queueFist = false) inline
Adds a new state to the queue
Type Constraints
T : State
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T >() [3/4]
void JUtils.StateMachine.AddToQueue< T > (StateRef< T > stateRef, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T >() [4/4]
void JUtils.StateMachine.AddToQueue< T > (T state, bool queueFist = false) inline
Adds a new state to the queue
Type Constraints
T : State
References JUtils.StateMachine.AddToQueue().
AddToQueue< T, T1 >() [1/3]
void JUtils.StateMachine.AddToQueue< T, T1 > (StateRef< T > stateRef, T1 arg1, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State<T1>
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T, T1 >() [2/3]
void JUtils.StateMachine.AddToQueue< T, T1 > (T state, T1 arg1, bool queueFist = false) inline
Adds a new state to the queue
Type Constraints
T : State<T1>
References JUtils.StateMachine.AddToQueue().
AddToQueue< T, T1 >() [3/3]
void JUtils.StateMachine.AddToQueue< T, T1 > (T1 arg1, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State<T1>
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T, T1, T2 >() [1/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T, T1, T2 >() [2/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2 > (T state, T1 arg1, T2 arg2, bool queueFist = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.AddToQueue().
AddToQueue< T, T1, T2 >() [3/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2 > (T1 arg1, T2 arg2, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T, T1, T2, T3 >() [1/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.AddToQueue< T >().
AddToQueue< T, T1, T2, T3 >() [2/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.AddToQueue().
AddToQueue< T, T1, T2, T3 >() [3/3]
void JUtils.StateMachine.AddToQueue< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3, bool queueFirst = false) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.AddToQueue< T >().
Awake()
override void JUtils.StateMachine.Awake () inline protected virtual
Reimplemented from JUtils.State< T1, T2, T3 >.
ClearQueue()
void JUtils.StateMachine.ClearQueue () inline
Clears all states in the queue
References JUtils.StateMachine.stateQueue.
ContinueQueue()
void JUtils.StateMachine.ContinueQueue () inline
Deactivate the current state and go to the next one
References JUtils.StateMachine.currentState, JUtils.StateMachine.QueueEntry.data, JUtils.State< T1, T2, T3 >.isActive, JUtils.StateMachine.isQueueFilled, JUtils.StateMachine.OnNoState(), JUtils.StateMachine.onStateChanged, JUtils.StateMachine.QueueEntry.state, JUtils.State< T1, T2, T3 >.stateMachine, and JUtils.StateMachine.stateQueue.
Deactivate()
new void JUtils.StateMachine.Deactivate () inline
Continues the queue in the state machine, or deactivates the state if it is the root state machine
References JUtils.State< T1, T2, T3 >.isActive, and JUtils.State< T1, T2, T3 >.stateMachine.
FindState< T >()
T JUtils.StateMachine.FindState< T > () inline
Find a state within the child objects of this state-machine, if _autoCreateStates is enabled, it will automatically instantiate the state
Type Constraints
T : State
GoToState() [1/2]
void JUtils.StateMachine.GoToState ([NotNull] State state, [CanBeNull] StateData data) inline
Queues the current given state, then goes to it
References JUtils.StateMachine.ContinueQueue().
GoToState() [2/2]
void JUtils.StateMachine.GoToState (State state) inline
Clears the StateQueue and goes to the given state
References JUtils.StateMachine.GoToState().
GoToState< T >() [1/3]
void JUtils.StateMachine.GoToState< T > () inline
Adds a new state to the queue
Type Constraints
T : State
GoToState< T >() [2/3]
void JUtils.StateMachine.GoToState< T > ([CanBeNull] StateData data) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
References JUtils.StateMachine.GoToState().
GoToState< T >() [3/3]
void JUtils.StateMachine.GoToState< T > (StateRef< T > stateRef) inline
Adds a new state to the queue
Type Constraints
T : State
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1 >() [1/3]
void JUtils.StateMachine.GoToState< T, T1 > (StateRef< T > stateRef, T1 arg1) inline
Adds a new state to the queue
Type Constraints
T : State<T1>
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1 >() [2/3]
void JUtils.StateMachine.GoToState< T, T1 > (T state, T1 arg1) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State<T1>
References JUtils.StateMachine.GoToState().
GoToState< T, T1 >() [3/3]
void JUtils.StateMachine.GoToState< T, T1 > (T1 arg1) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State<T1>
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1, T2 >() [1/3]
void JUtils.StateMachine.GoToState< T, T1, T2 > (StateRef< T > stateRef, T1 arg1, T2 arg2) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1, T2 >() [2/3]
void JUtils.StateMachine.GoToState< T, T1, T2 > (T state, T1 arg1, T2 arg2) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.GoToState().
GoToState< T, T1, T2 >() [3/3]
void JUtils.StateMachine.GoToState< T, T1, T2 > (T1 arg1, T2 arg2) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1, T2, T3 >() [1/3]
void JUtils.StateMachine.GoToState< T, T1, T2, T3 > (StateRef< T > stateRef, T1 arg1, T2 arg2, T3 arg3) inline
Adds a new state to the queue
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.GoToState< T >().
GoToState< T, T1, T2, T3 >() [2/3]
void JUtils.StateMachine.GoToState< T, T1, T2, T3 > (T state, T1 arg1, T2 arg2, T3 arg3) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.GoToState().
GoToState< T, T1, T2, T3 >() [3/3]
void JUtils.StateMachine.GoToState< T, T1, T2, T3 > (T1 arg1, T2 arg2, T3 arg3) inline
Clears the StateQueue and goes to the given state
Type Constraints
T : State
T : T1
T : T2
T : T3
References JUtils.StateMachine.GoToState< T >().
OnNoState()
abstract void JUtils.StateMachine.OnNoState () protected pure virtual
Gets called when there is no next state in the queue
OnValidate()
virtual void JUtils.StateMachine.OnValidate () inline protected virtual
Reset()
virtual void JUtils.StateMachine.Reset () inline protected virtual
Start()
virtual void JUtils.StateMachine.Start () inline protected virtual
References JUtils.State< T1, T2, T3 >.isActive.
TryFindState< T >()
bool JUtils.StateMachine.TryFindState< T > (out T state) inline
Try finding a state within the child objects of this state-machine, if _autoCreateStates is enabled, it will automatically instantiate that state
Type Constraints
T : State
Member Data Documentation
currentState
State JUtils.StateMachine.currentState protected
stateQueue
List<QueueEntry> JUtils.StateMachine.stateQueue = new() protected
Property Documentation
hasActiveState
bool JUtils.StateMachine.hasActiveState get
isQueueEmpty
bool JUtils.StateMachine.isQueueEmpty get
isQueueFilled
bool JUtils.StateMachine.isQueueFilled get
Event Documentation
onStateChanged
Action<State> JUtils.StateMachine.onStateChanged
The documentation for this class was generated from the following files:
StateMachine.cs
StateMachine.Helpers.cs