JUtils: JUtils.SerializableGuid Struct Reference
JUtils.SerializableGuid Struct Reference
A lightweight guid class that can be serialized
Public Member Functions
SerializableGuid (ulong a, ulong b)
byte GetByte (int index)
Get the byte ath the given index. Index must be between 0 and 15.
byte GetHexChar (int index)
Get the 4 bits at the given index. The index must be between 0 and 31
bool Equals (SerializableGuid other)
override bool Equals (object obj)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static SerializableGuid Parse (string guid)
Parse a guid from the given string
static bool TryParse (string guid, out SerializableGuid output)
Parse a guid from the given string
static SerializableGuid Random ()
Generate a new random guid
static bool operator== (SerializableGuid a, SerializableGuid b)
static bool operator!= (SerializableGuid a, SerializableGuid b)
Properties
ulong a [get]
First half of the guid
ulong b [get]
Second half of the guid
Detailed Description
A lightweight guid class that can be serialized
Constructor & Destructor Documentation
SerializableGuid()
JUtils.SerializableGuid.SerializableGuid (ulong a, ulong b) inline
References JUtils.SerializableGuid.a, and JUtils.SerializableGuid.b.
Member Function Documentation
Equals() [1/2]
override bool JUtils.SerializableGuid.Equals (object obj) inline
References JUtils.SerializableGuid.Equals().
Equals() [2/2]
bool JUtils.SerializableGuid.Equals (SerializableGuid other) inline
GetByte()
byte JUtils.SerializableGuid.GetByte (int index) inline
Get the byte ath the given index. Index must be between 0 and 15.
GetHashCode()
override int JUtils.SerializableGuid.GetHashCode () inline
GetHexChar()
byte JUtils.SerializableGuid.GetHexChar (int index) inline
Get the 4 bits at the given index. The index must be between 0 and 31
operator!=()
static bool JUtils.SerializableGuid.operator!= (SerializableGuid a, SerializableGuid b) inline static
References JUtils.SerializableGuid.a, and JUtils.SerializableGuid.b.
operator==()
static bool JUtils.SerializableGuid.operator== (SerializableGuid a, SerializableGuid b) inline static
References JUtils.SerializableGuid.a, and JUtils.SerializableGuid.b.
Parse()
static SerializableGuid JUtils.SerializableGuid.Parse (string guid) inline static
Parse a guid from the given string
References JUtils.SerializableGuid.a, JUtils.SerializableGuid.b, and JUtils.SerializableGuid.SerializableGuid().
Random()
static SerializableGuid JUtils.SerializableGuid.Random () inline static
Generate a new random guid
References JUtils.SerializableGuid.Parse().
ToString()
override string JUtils.SerializableGuid.ToString () inline
TryParse()
static bool JUtils.SerializableGuid.TryParse (string guid, out SerializableGuid output) inline static
Parse a guid from the given string
References JUtils.SerializableGuid.a, JUtils.SerializableGuid.b, and JUtils.SerializableGuid.SerializableGuid().
Property Documentation
a
ulong JUtils.SerializableGuid.a get
First half of the guid
b
ulong JUtils.SerializableGuid.b get
Second half of the guid
The documentation for this struct was generated from the following file:
SerializableGuid.cs